on:
  schedule:
    - cron: "0 19 * * *"
  workflow_dispatch:

name: Weather Graphs

jobs:
  render:
    name: Update graphs
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          # use Posit's CRAN mirror with precompiled binaries
          use-public-rspm: true

      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2
          
      # - name: Install packages
      #   uses: r-lib/actions/setup-r-dependencies@v2 # automatically sets up cache
      #   with:
      #     packages: |
      #       any::ggplot2 
      #       any::readr
      #       any::tidyr
      #       any::dplyr
      #       any::lubridate
      #       any::stringr
      #       any::ggrepel
      #       any::scales
      #       any::here
      #       any::data.table
      #       any::R.utils
      
      - name: Retrieve data
        uses: nick-fields/retry@v3
        with:
          timeout_seconds: 30
          max_attempts: 3
          command: Rscript -e 'source("R/Retrieve_dwd.R")'
          
      - name: Build temperature graph
        run:  Rscript -e 'source("R/BuildDailyHigh_dwd.R")'
        
      - name: Build low temperature graph
        run:  Rscript -e 'source("R/BuildDailyLow_dwd.R")'
        
      - name: Build precipitation graph
        run:  Rscript -e 'source("R/BuildCumulativePrecipitation_dwd.R")'
        
      - name: Commit graphs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update data & graphs
